name: Electronic Control Unit (ECU) CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push but only for changes to relevant files
  push:
    paths:
      - 'components/ecu/ecu_firmware/**'
      - '.github/workflows/ecu_firmware.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  add_version_information:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: getChangedFiles
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.getChangedFiles.outputs.all }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: jitterbit/get-changed-files@v1 
        id: getChangedFiles
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Insert push hash to modified files
        run: |
          CHANGED_FILES=${{ github.event.inputs.myInput }}
          python .github/workflows/update_files.py
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run
        working-directory: components/ecu/ecu_firmware
